---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: game-server-accounts
  namespace: udl
spec:
  encryptedData:
    UDL_NA_ADVANCED_ONE: AgBgaoeB6RPyJNbnq9c/7uGcYgIIDa+DLDHfbCFWFsHBjImFyGUUSZw1kJ4H/sDVYlQo+X12QNZU1A0D+QCrPXjz8VGSOrFX/4HAV1GjKD5Kx/U1cJPD8BKLjErvS1Nnf1nZrfAtkXMEoe4Z2k65L4xFVL1QQXvofLh1UiuMqkOclLLXMau4PaH8fIQxJkVak21rcvD9QqgzYwVxWkB246kvR9JCAlksIQN/InTot4YVrwns53m6nywEUvbeJMwEZLnDi9MMmrMtW60/+id2xSIKYC6Fbwrf3CpMnrq846LcyLjDysXBPQC7fXH9mC+Pfztp4XVDxyE4X7HUUQxFsN29OC2cgqJO7KvFPfzvnRcHhEQUbRuEIFRw+nulOPvz/bae8CwxOGJQuBq7V9c4dcpLg5g4B5EHP+NKR2J2E+18AXLfx+dzwgSDtmn7tfPO94Nmv3zT6Hr7Kug4DK5OHzkER/PZQ/8CIp9IxZ1+dQ5fOOMbQxkao6UU0s5U8aQ47Y/wbllks5oz8m72pUE6KkVfzCYDArN/yCIsrraonhX00+7TGWSTzBLkid5VVkn+o7uvkkkwg/kHuF+mNUjITAonhTVkpmLIlG0+oFejM4SPMcsU4emEQa4PMlUu3mn70p2YxTsNI124Lb+5K//Y3Wa1QOF2gN25vPC9AdIM9XpUhmCBZvplv9/xK/1N0NhMuzY2PqV6ZULx6UEkCPUDguXjnIp2fQX2brUjG1OzKmb7fw==
  template:
    metadata:
      creationTimestamp: null
      name: game-server-accounts
      namespace: udl
    type: Opaque
