apiVersion: v1
kind: Secret
metadata:
    name: ftp-credentials
    namespace: udl
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:/3mrDvZ6MnDdFD9SBTX93ATiNCu4K4KL9fFGYXrTkMLqZMm0+ly6zHxp/OCWLek59y6ja7Td6ux3ZclEa9l+MfORcv+x+JFkLNJAme4zc8s4o9XiyjfRBV7ZHMO+dLxf1MI7g9QrQRxehm90QSJG3uVq8PFFk82hv7nC/ojl6TtER0uH/OwhmRJh,iv:zDwdv2vUS50BUYGzZ0/hsD8LChgZN6H5OJFCnGUba0g=,tag:LO3ukgz6QEmmNhuUqc793g==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K1gwaDBTdWVJT29OU0I0
            TkYvMVNqUFBVcWMrWGJ3eGU0YXM5S0JCSjJjCkFza2w5ajc0YmoyNWdzREtCbUhv
            aUwweXdhcXFYbVhCMEMvYjJkMm5mZ0kKLS0tIEt4RmN0SzFmR2FxeEo1V1A3RU5i
            VlNEWklkd0J2SHBHTHJZOTdBczdnOVkKaHhzuvqIwdS7En/bfOSfq2zZ8eDqQ47b
            rcdzd1difQuZSnairgqqJ86U4Ihpt7LMStZoR/FYH5AXPYTTrGsOiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T17:50:31Z"
    mac: ENC[AES256_GCM,data:NP9IiKbVdbMUuNHlh2ybpILFa9c+1jy06FyAVwxvS6AoMvTKxT7UaCD56Avo1QYAbyp9fw/QrFThtCbcvp35GpSvD5JFqfGVOP79h1nYrLFtVJQeZ9IpdVMcix8FuelvghSPevkYC0WLF7huExCXCmdZtK+aKbh13dGG5MNxPc0=,iv:ceJPsIrQKWWoT0R1w84CURu5Au5Gi/vmAnbPVIgVdXU=,tag:5ssv2NacRkb8RC/KTivO/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
