apiVersion: v1
kind: Secret
metadata:
    name: ftp-credentials
    namespace: udl
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:+JSBS0w4BFkTHdo0UdxRZa63msyD02ou6dRnoN0WATLjQQP1xrkCgBPmJq0KuM6GhoBZLR77b+p/38r8Im2a8Z8prVjQLCcyvweRBq3fUCMPY28kfSRQgjMIyDqjNsIRq/jpHJCMcYO1UgVlk3adZMu5fm+HM7DO+Lvmt9Vb4AXntBW8HH332n31,iv:P5PBMoHKXBTZynBNjTz6JEYtW6If5dO8Nm/JPZblkRY=,tag:PwccXamWlGPGBVEMKU7xBw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQjE0Z2hsOU9kcytwQ1Ey
            cjVqOUJEeGQvTmJRU01JbVdJV1B0cmpkNVdBCkh1clJ4M2RHc0FXcklmMEdseEpY
            aUxaRTMrejNyTjNsT0kvMXFVNFp4L3cKLS0tIE1KaFlqV2JTNjZYcW9NcEhYMVY1
            YXRWYlkxUCtHTXlHSzRNekhvc05vb2cKanLT+/pTOTW7PJ7C5E6DM6DvqAmquCXh
            biSEonI5kxHh6EQoLpU+uhhEc2MNYcuOaVBPH0RaAu6702mSgtUPng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T08:37:58Z"
    mac: ENC[AES256_GCM,data:vs7FAmtk1D5sq9/ZPP/7w5Mj8MCVs3jK+Nvgf7Pg233AKrzpJxZLW7Lqd9pznyUb09on9e45FBXnJeuHG3gNMvJd9VZuOopwT/Vq+Ec3j93ght1PTspurUmvHt8drz/UIr1k3a/7YxGYuZtwbHqDZXunyIfC1vXQUFb0pE3fgOI=,iv:gResd8wpXraLiBP0t5xyPjzSFJtlAzQK4Dj9x14MKhc=,tag:5fdwJxiqmThFzAsEfc0X6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
