---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ftp-credentials
  namespace: udl
spec:
  encryptedData:
    users: AgCl7hOd+aMzRUy0ziDSObO4T653Fr5Bn88wGRNulnn586O8Z9oay8+ap0NniJqaMbUEVlK+W+pbFPPgCj5s0PRZ6jnejKrsNp9gDvUwFXZcDumcIZGl1xVO+qrdBAP8I5bZGlRvdKVsaWyiYfSHZPr428S7vu+KuiBYnq/KdSCNKzoCTrzj9f+ZREJKVSbXzmIwZ+PU76LFRR/C40oFr94EYVP6dnpb6Q6jsxoCcqZhqj6JEq4mkaHbRoZ4HJPnwRB5jQSFoeKzrkhRx6QV9oXSe6EgHU6H79uRWChpAKgBZphbeXVK2fD1hfv1tppfQEos6+sU+iXh3wE8Wqxx/dkq8KHgwH8Cbj0AAephkZ8xCfoFwPprIPBxr3A2SYUxfMtkOaVaNQWIZj+wDTPC5eZ80FxPFr0vfcBh8JYoR0dyorUjT8vne3jlKUl/FYwMNxzWTT0PgjJb+xTzL/at9cWO0ppbbqS4embxjXsEWo+WRBG357Ki4JSQKv0YmMeMMddRTP752/v/PBuMF+Tmz/CflM81dIX1CuDQgp8qd5GitHptyrHXwwyCSpidhsYhLX2rCYk+49O5MLSpCqNQmF2NHIu0oRX27vXtTiyOinbUP64f0J8WX2L4tW0aLa0Lu/bMJSADPMG0FPnf685IkZbKtMY9DlQ7m/nENXFX5gKlhEiJaINheoqL1kdsfzL4aEIjM1VKXN4ylu9AH3gxUf7L8e8mlUj5VFTq0rsCaliYvpIU2bvyWl1fd7iFWgsP6qiSwVLTECP+2KXeOJvuzRlQQF5kWYIRMmwG2GI5y2TaUDn8FVh//xj9wRsupcqbm5PaiSYuER5mA3ugDcnSB0idDhdcrEMydGVnBrK6DPwLS3wU+eo4wBvcIwlhMFJVgVYUIBHRJakiLpaeZyV/KwH3cbcm8FOtJcTnZr6ttWHrYPlEzuIlBFHO
  template:
    metadata:
      creationTimestamp: null
      name: ftp-credentials
      namespace: udl
    type: Opaque
