---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ftp-credentials
  namespace: udl
spec:
  encryptedData:
    users: AgATJRm+OgLlcaZX4suyxe9cTepwR0pueqEpdmAYo3ocZix9/Vo51+KSLF5nv2DQ32jKdA8m6/vdAI8TN4QbgtZye15cM2BtWiGa2ei1kKWAMryXFAVQoFBc2i1slWgWc+vcruzfgOJc2v0ZbFs07GwDn3DMevzg6RbXqgXXSO6iFo6IvmsUMzhTmL1DGu1lLoW3qh8kAPWzi6fDJb8c9LZCniOkNuWsjVYSK3zaFlcbz3WrZMW3kQ1vkigueogGw8nCok0xu2/KgOPIgFh5ccJPDfz7RKciCDOC3O1YX33haW6dQwr16fqkLb6J3T7ARaPJ+QVWASpfq5PxYwX7GzjmyOi05JjoS2yb2GFu7I0OmAaDHBGokZs2vYsycfydj2mB2gpkJSbBydurNz4WzZ5fOUqySEMmUJw7ZIvSXQMthdwUlX+SPl9FT9VOoR2JaPZR9qkww+hV5N8oeyvYGdDWET+t45PuRWuY28i1OIrBEsleVE5B2imwe6j7mcDSSrUqi3qFPCmRBpi3l/SmOX7vpglElpxrEBHS9Jldjr9eTa00DpqZk62fUqAeRwlq0Au77BhSnAOw6bTht3rKDN342hTxeeSIOlUxN5s/RhVuEEZMIPlmrMCU0hgn9UxRRLQyCZdN7rNiYVQtvYgHif68zXB1hojL2Wny5nVoE/kixOmu+MnVPtYYWnYZBlj6CteNUMr3jM+K18+6Ch+7iovf6sXj/YH+TEm5ROVQd4Nmd5RvPNuO+6h7Aiy1BosS7Q1K9bfCRLLZ7Z5fXwZd4A62wqtyZpxLV2hH0Ouj8akWEzueECly84Dx+avZUo5NlsLKn3EKep8yEcVzf1MYPQjkfU8MJi2KKa3DYJkllmow+6nUGmHD0cb05qk=
  template:
    metadata:
      creationTimestamp: null
      name: ftp-credentials
      namespace: udl
    type: Opaque
