apiVersion: v1
kind: Secret
metadata:
    name: ftp-credentials
    namespace: udl
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:K7zpPexuDpzOpaZyLFtuHzV0e1nGDRLQu3MTec5yXPmlwvCtbF8QORe8uzIaAjhG4X00OrNWgQYqtqqOO1yhlD6m2xt3xua/7j2VMUP8ETUYnIdbyscQDPE7ooZ/oToVijJKGiz/A9eU2z/6mZphdLyzHswQUQPjoEDW6tE73WYRMgEexoMn3jl9JOR3BmZkWmeFcxwirEpphcnd2AZk78C8v+EdbpUvEkUnVXRT7vD4HvO0GQglzQ==,iv:9hfGEIgjsQ9TgEpPsi5maMhdg0sxUnODZP2B7wCarVY=,tag:OA5TQdjsFJ/3aYTQTnVK7w==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQTQxaWM2NER6d3poWFg3
            Y0wrZ3RmVWFVUU9YS3NVZXFpYllYTWdwN3lFCmZZOXZ0Rm5rZUxGSm80TmFXWTFZ
            VGhxUE1qZk9oeTNlcWt2STNCMnFJa28KLS0tIHIyTVFyeUR3ejNWNmxqbGN5SW9s
            OWpwcTdKYmN3S1FMUWxtM2tFeUFRazgKgSYBXJJcBsmRMLDN2JIkEt84sZAWZ0p2
            LbLaTgLuNBQMwaZRH2/hU0+K7lH4n9zGJWJ+uYuDb3cy+zS7TuVrHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:12:59Z"
    mac: ENC[AES256_GCM,data:uObTTx2zviAfPq2h1HDEXZsgQOLo4rH0PC+DQboNCC2wieg9i4dAd/P/KuesolYvaz8+cZEiX7GsH1HvZvWfhIhawedb+PrfsVv4xWIZndIaCAh9MjywM7NMOOST5PnXJQ99X5DOaJ6YBhURTX65DbAFDzUV/oEx4e/ecTTHEio=,iv:rX7C18h4JridDr0eao8oXbx/kEpPsyaqNZ6ypZbD76U=,tag:K0PPJLIE1B8tFU0vW7H4MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
