---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-git-sync-serverfiles-private
  namespace: udl
spec:
  schedule: "0 */3 * * *"  # Every 3 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-restarter
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - kubectl rollout restart deployment/git-sync-serverfiles-private -n udl
