apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: game-server-accounts
    namespace: udl
    annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
stringData:
    UDL_NORMAL_ONE: ENC[AES256_GCM,data:hEAWempcrU2lKmPPd5vzN1/KPgfOwk83wBkYZ6zHuSA=,iv:JW4FGTDi+sdGzZX+2jgdUABINGdu9lfZ5uEPJD7Wi5A=,tag:/w6oc8OWXb0XaHfKdEJ5bQ==,type:str]
    UDL_ADVANCED_ONE: ENC[AES256_GCM,data:tyR/beyykQsBSoBAH9F/W7+QAuSoYHKdpFh6J7cE+T8=,iv:tJHKlFmql6zWlqknHRM1rzDHgmKbif5zlab4HFK4+UA=,tag:7Q+lOyxI8PPivRECUGcaLg==,type:str]
    UDL_ADVANCED_TWO: ENC[AES256_GCM,data:nKK3OfPGqZbvJfgpnjXS+8Pb8qIgrTYPP/OGsjpJPLU=,iv:vVTqUx6y0WWgGOOlWZey4F7MCUGex3TrpeAPkWMl5a8=,tag:Wr3tcMB5RQoAvJhiEsANSA==,type:str]
    UDL_TEST_ONE: ENC[AES256_GCM,data:Vc84RzFRy23oWGYp1lhMa6L9oZVZFNo8ZlvNpqF8yZE=,iv:icekKq1s5mmNgz1+OVaUrIYhiV7gEcmkMYrwrdInnWE=,tag:W3jJZiS281at+JJpTL0wTw==,type:str]
    UDL_TEST_TWO: ENC[AES256_GCM,data:YTXZKVFjM6R87H/NOT2Kym0S79c5jKBIKaMZm4EVSPw=,iv:cGecLX8GygLuJ6H0pYTOCNbIqcY4nwB39/7raUnSxrY=,tag:g+MwGEJ+zkeaTStoUrqCAA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRGoxY2E0Q0ZUWkJUOXFO
            YzZjS2tqTkhUY3BFS2MxWllpNWR3OU5SSVNzCjQ2VDB1U09qdllPSVNPUzFSa2hu
            aHAwbGFCdEN3bU41ZU5JVE5Zb0dyV0EKLS0tIHV4anU5SytTR3d6b2dINy9nbmpx
            a2ZCUUJ3eGFVcjlwSnkwM3NndTVFVGcK2ReENTIkUh/kO65yV29fv7n2KXKSGkJB
            Q5AvZrb6mKeiAGbMA+u/H1wVQT6Whz5H8IUYehDSQAf4Tz7vcBd67w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T08:37:58Z"
    mac: ENC[AES256_GCM,data:vbfjVqq4G4QO+lARc1PLegiTFy7AOHIxb+5l83A5Jy5kdXLTeYJ4JQquhcg2KUdeOsf1MtKhf6zLh1g5ON9n8kUb7RaDIvIIQiUV48GpNKEpAnMR+NtF4DDCnFHS1g1BlPtdwOFa9EXHTC8mM6J6cvuUmN9wOsJYABNZOmW9a34=,iv:XfdO3qyc44eLDoDAwq+yigwOBY7mdiNdurWIQEl0Vvo=,tag:nVtm5hSA7hgJUXrXY4bZFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
