apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: game-server-accounts
    namespace: udl
    annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
stringData:
    UDL_NORMAL_ONE: ENC[AES256_GCM,data:u59r+SRUqhe8IVMeQVo3AbWs9jFJlHmndx4e98wNy68=,iv:iaCHORgrh/7eWXse2z8Dd5mN0wD+Qx8WXwTW+M4L7VA=,tag:FeBRj1+Ri+JHHGe/m+6LPg==,type:str]
    UDL_ADVANCED_ONE: ENC[AES256_GCM,data:35cuthklNl/O/O0LZEYmdHJZ2V10GbOptMuCyjHZV5A=,iv:tq9J4M9gQlSRalxMOS3fddpTSDtc/fA4i0U7vWWzjg8=,tag:++BHup0ZEUmd3CQJeWnYZA==,type:str]
    UDL_ADVANCED_TWO: ENC[AES256_GCM,data:NRndgA69IIdamtS6lTHNJmXxHXd9QaamoH1FJz0CvOw=,iv:4Lvoo/8MZ4miGqtxcxYupozIeNOaFb5gM+/IvDWOMGs=,tag:qYWTj59cH0GS0iGQhDHoqg==,type:str]
    UDL_TEST_ONE: ENC[AES256_GCM,data:FvGnqe9lw6QIaigRBOb9XZS8RCLT/RiXEi25CCrDOwA=,iv:NqT2QvWNfcAyIZEjCaY1Dt8inF35uNMXqhcnWoHpETo=,tag:XtSFApKMPuD7LywQZAdwoQ==,type:str]
    UDL_TEST_TWO: ENC[AES256_GCM,data:9Kq1kd0NG27Jr3m7W6j65PenkBEQUtAxfDxgK6aVvAA=,iv:IvplMdHCku6urc8iwX3ppyGPryGwJ7flWXXqLq/zC2I=,tag:fw/n5L6zz0IJqJ7PGYn9hw==,type:str]
    TONY_76561198123577596: ENC[AES256_GCM,data:OR24SGZCh0SW1mBbYn5Azo/Uk9Wkntnzx4sw9AzqCAA=,iv:vC5TAvm/UeoggZrcu8gOasv93TJZE/hs9vCz4gQqc6M=,tag:VGzsjRKXgbln2GvYVr2+Qw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTXd1SCttNC9nWWJZa1Vx
            WW1FQWhpYTgxdi93TTIyZXhsY1RqME5MK1RrCnJSZnF1Y3NSQ1JreGg1QmJpRi9C
            elV0REJGNFBxK2l6ckpoVldjdGhEZVEKLS0tIERIVWlxbFVSZU4vUkgxNWc5cERU
            ZnRNbDA5cnVzVDI2TGJMb2hmTE1TNGcKOFb0WG8XlK6vyVEwJQydJO+WLQNRkVAj
            R4VDbnLMrfG1CRaviO/Ty+l/znJ7W+2SSuKYlBnmFC8qZA7Il4aI8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T19:08:53Z"
    mac: ENC[AES256_GCM,data:oqTLVOkRdekUuHxb19qkdlXpi6VfQz6DF1SadUbVAt7OyPILKd3LKxZPayZ0QCdChKnCC6TlI0c+MOINZIdiASI3wlucgeGpSEm2jLYKWibtUkthp0rzgwd02LpoP7ybu4gJDw0PtYxcVTXC0P7bdsM9sJOlStedkDG7SO6YShc=,iv:hLUvHimDw7VUhU75cdc/vXcZl7dRTr9N6rypFcNd2/c=,tag:mERF6MIOxtQCXpErb3Wwmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
