apiVersion: v1
kind: Secret
metadata:
    name: citadel-secrets
    namespace: citadel
type: Opaque
stringData:
    master.key: ENC[AES256_GCM,data:d2XsCEPvYg+C9DkcaPbs1ADyveJQKXad+Wz0Fgmukzw=,iv:CYRebbzg0VQmV+jZS+T+D360mCgQ3I98O5fWrxGomJM=,tag:kBgcTS9wi4FoP/kOfgVHJQ==,type:str]
    credentials.yml.enc: ENC[AES256_GCM,data:l94X7xtK3KkIwc8xvaPgNnZsQkY3Iha634Huv13BZbE73FzlLhW13YQvS5PO08AFO59K2T/WoXMF1iWO1XigiNyiWJjcFqjs0dAwoKGv0UymL9whvr0RuME2X2MB+SP/afxAGwb4/OQUjNiGu8+lVTZp4DOFvMrCdYpI2BXYBwdgphSuvqC5FrReL5mjyeLY6JgndK9FT6XkJyBmF9C+wVxzDwSKCO37BRWb6THUzLWDAqpwBZXLXnA/bvR22MyniJ5SqUE+T5O+GoO+Ly8HOoMcl8GbcQxez1eVhCPaGYB4DIvw9R7z52L7y1nt1fKSvGCIXI86HMW1rL81VW9gi+gw6vdHuePL1IYgfq1XLNj8R0tRbcF/lRtUa7Je6DTFiS7Hstz8bCCcTjaj8ZYZv8N0Lr0N4jQa/d7MRTDZYb0esLEqsxSAJKYKFCZG7JlmOXDzTVy6EPhGfwM0ORGzcii4TKs8vn8MJYwrwHcGkw9a4b1Ji39RPS+KojREqj6Fh+eo1+K9BAgHErpoBt5CbMtmy2lGFvTaUv0QlL6yLkgpdEVDYIsb3711rsub5fMCm75pS9X1oprYSUE7W6CRugrCrUzQ4C8ldITRM0znUGdBdkvE/2+mPnRfvCJwkC2NCVdIT6BHbzsnidrDEjcy6bcSmZL24hE5GhK4Ug6fN26WN+yKc9pzw3C2nAlk1W2BfelF4mBmJoEEVIHXY5cijerJ67FjHy3Ahm+A8glWhWjCt7XOKJpf906u36V+RwfwKEmp29twDfwPEj5DGHyG7SdGFmSOMrBH1A8vaC5+vN01XepJTChmi6ga3vKgDu/gtIuVs07YEpLlagyG/XtXhrMzR45AxnAz,iv:+Es2zc5hKgJYAzhKhoDASDk1nrTSetMvZ+JqzuU9t+4=,tag:nspSuG6RvKqaoMzoehXi+g==,type:str]
    SERVER_RESTART_SECRET: ENC[AES256_GCM,data:VaWdNU6/GTp9eqbKyd0v5Kcpwq8=,iv:236AwGe08HTeh8V2/B1M4DH9yBtu8CbfykEiNSLAldw=,tag:l6L1dn/c6N/F2CdWesnQAA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZzdNVnp1UStkOGhpcHZI
            aHBmbVNFMTRIcnY5bS9YTUlMdWNMQ2xJWmdnCjQ2ZkV6Zm1Pa1hRV25aTnZ5QmhT
            VW5JUUtiYUd5QWxRZ3dCeWhUdHlISVkKLS0tIDY2azVkb3doV3B4bHNIMmZpbVYx
            RnkvbG1EN1hTellwdXgyMGVmQ3hiOEkKjhCPU3tyyfae09HMVtkAVYZ4v3mFjcT1
            MeAqrmOGngzKJILMUGPGf/mBsMzesIrIFcdHUkCPX203/CVhoA2aJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:12:59Z"
    mac: ENC[AES256_GCM,data:tsAlsoQkyfAJMbP2Cn39YkryPRA7iDub4fUk6jSu4BGnruzvpGCptWQ6l4iUxzTq01Km52JaDz/78239Od6BefF07qOCKbDkI9zyFfGROG+OVfpSZd9KLyni5qBnMAWtx+hz1ObVQN60z1H2cVTyRMmOSLvY3cWD+N2y/rxJkpo=,iv:je1TAOh78P+6Sw6I++ovc8kU1oNpx0ehUbm+POaykyU=,tag:ajhudzaM/znU+GZkrooCRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
