---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAIxj9vytOCQlBHEHSFXZlY9ALniNr02ENHQoP5Tl9P4hHKnt2w5uh9YUOL2yDLoUEJWFNO3ckerYsf7ZrrSxZoFIDx7ACNbqVeq5W6Emm6wjE8MFHe7bxYrrDtR7FYlKzZw/kN0u4Z002qp4xpBA85cPWuzFIAhbEAKFvLv8ZfTRLK7JRU+xyHlJC/5oz2o+exbeGTlvbguZaDdNNTVjiXHS4NjDlo/M6pw8arfB7JncEQwluufPCffxvfnAkLnHLHm4bnqMM/e1EwbE+xW+v6H6Tm5xKzu27ANeoAPhDtfVWrKlGF8I9m7BKozFIOUG+X2rNJH6dubo2p5UCvcRrnmXcMAcKQakEF4cBMIVs8cUPM8lO1DkHAfIx+otACQv9s/t2fHfNdr3QoZV8nvDKsb6vTuVYSPc4afC0EImIIx26LbGFVOubUTW846tNFZFF7YlwZuAuCoPN4NIBfQqhmxvVopfl3XJKutnsesN+lwt4qWqNnlNyP8iqxHXlNgHtcKvAPhWongpCmskoH82FplFFMmVF0XkXtosN52jMIsvUOfhl5PT4irDvBP4nFPsOfbW/I8E/HEymBnEoRdhUS532eSM39ZQKVarmRU1KWJh2C3x6Aj2QF8mzXwpEFW50/18ZQzV6nfs1w0atmnNbA4aJLZPwOLUb6F/uMjUVvTyjykhhHSvmzW2sStWqzXp6UUSsdpuE=
    POSTGRES_USER: AgBMc1PPA03/+eD2eeKKbuwJTia8+OcA0dN0L4L74120Zt06HQYIRxc8CarA9F3cqwMv46jRzCJfUrbaaxTl9ZRe8oJyBy4RUx3LMRqB6wsQexiYyl3AxE2Mi+BO9uc11mdpwbr2Nb+vmE89S55huW/00vcPpi25dq4OxtpnaQyStUAXp4Wzxr9u+6skcNH2jOCrFagMLkXIDc88dT9b+VcCk8PCrvFwJFMUr4OSuF8cYRaGf6x7/0VnCQ34DWi3jWjF/m1RCv46CqAbdo+ounPyNrWcYlvQh/ynQ0Og3ggf6CxXBIjOtzfOBVX+za4lyY5bjgwaBV2PJAymAERkOcgHq38QEME9H+3mttKlchcvY6OwPwBW2hwNnEOiugLPx4J7M3jAFQ97WiEaMV6b8R6MinAUoUbVCz8AQOxXMI/6acnFC3bgM842Lh7ddxPwLP6Tl+PrP3Zoub8rgRldgsbKcF29NsBHv9SFZ5P1rA/5KIQQ8qQ9yITV2ZM6A9j/CbMrewKNsjF0uJx/jtR6R19fu1KvV5wFn8Lzb6/E9nUs/gqmMtqgA0jSNd0ytPFpesrHWj/XTukMXo97hmTUAdiT3+WtaGbjzC7YcTIDmBCGgIMb8Gvnqx+SnMbYgW6yb1buJWhhLP/LBNAhR+ySVF9b/OZKUwINkm98pg2JMyvL4L3BOfuP5Km3m/RyNL5XvFSYp/vgSRuRyg==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-to: udl
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
