apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        replicator.v1.mittwald.de/replicate-to: udl
    name: postgres-creds
    namespace: citadel
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VvJMSKWl,iv:OZqEs/QkxMA3bZHWiCGb3kInXrqy/5B7DKRIVq4bso0=,tag:5w7RrOoHIivHZEy4yPmHyA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:a4YniSmOmoM=,iv:UFeepBETsErOsrQ3YSvY3N2f7Ura3QPaLhH51wlFowM=,tag:9OJ0IhR3yqWl7RN9vCpA7A==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaHMxMzd3SW55ZHpxM2lL
            ZVQxcFFRUVYwL1BIYzV6YUdUVTN6VHV5MzMwClp5N0hzNXBOdHRsN0l6WUF5VUlC
            eVJ0dzZQYjhqUEpkb0lCL214cTJlc3MKLS0tIEJLc2RYdjJncDFPS1lFRkxmZElX
            d1lzSUN0bFpCajNUT0swWFo2UkNrQTgKnZMmMbkJ1wCIlkliIXYD/5VwuqNI1YKP
            gkj4nPFJipt1eIGWFnT9J4jIANipBMuS1ZwTUwJ5gkkmhQymO32PUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:12:59Z"
    mac: ENC[AES256_GCM,data:bTN54ComuOklSRyJW7K/kLHtQRVlcASC/WBeq86bH7RMglL869Fvopr1xXGft9NcvnDJ/NfYaG0GHq3AsXoOZMzuTuvDDS4Qht7ONZCcYiU/eqlAms7ohI3YD+/jrMzYVBMe1gJL/Yk2P1Zpo1c9PHeZbKtijBDRGjhiNh/6vxY=,iv:Es4sXRReMo48kexl8CIQ01AULbS/WGkoP8rGvAF4xLE=,tag:rEC54sJ9F0bvxweGemUpOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
