---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBESuALVXVpNmWIlnb7ljhuhg8imBzM+rLAxTVEfc6CtSLWvHDHPCO5R6gY1fyw5sgkEvYw/vfKhLkWMxxwRJtL24fQpW5Scr4YTe/5ak7DkGRz/EqjIVsp70wqQEn2xXSZsOaQw224+HtNP55/9qLvi9mk3nmmkaVtCstGK18GcNeAua9F1hOUAkSz6ii0O77vae3ZwKWp2gBS6J+0UkBZiTfB3mSrSBtNeEDbqGM5qzAuuP8usMxiYLZchvvSxzgpmftxNGYN5eD++NtofxNlbB0LyqunMmMYaXkgBqObyjDEYQoYWEC2QTxNOoKHMpRojCdM7VW76K6knvka4x5nued91a0mbgwGx0BmGlEKGTkdhHeObGhXHKy24Wa4k2adx+vzzm6Lj69v/U+EiUKF3EHcCf02DRtzasMTklBpC4E39AblVsMt5BXcFa/wuPxhEp7cXS+D9AQJlBIWVw42rL6iGx0QBgaO2tKxXTUeyOklZTqbKI3jByP6dHX15naDIZgtw/G5V03qpURvOTtGikPGe7dXjBhlbKLasI8bBrSihlZTeC2S2ZNdq6ZuqNe19NRXv17Ng2QM8raYd7lXWUdvmOrvq+uCwhslzwT6K1P/nnjAYskNgWhCamzr8i1CDT/gBPtFysbg6bMw480cX+zjvsVFSDnuWbz3g67B/FTXyzMPAYOeQgoTwRv7IPrgCoTysNQ=
    POSTGRES_USER: AgCtJVwfVDG6DuRdSavN8wjEzFJMwu8TC2ebVonyIHS87U24ui6sF1sfygKq7loqb0Takv0PL/kBdB39U7tXwhCJGj0D+RtVnlDqn0E76+SsouNKkATfo0mdwbCz+i444PW9vRLt/63LTlxOMifX1LWwQqk4L31Om63u6kTxQt0S53y8PcdH48/GBEaLHMSlawVZSFQDw+HYxyl6mc6HE4am3o6Jj7dywL5dX19NQheyNmGHmHMbGpS2WqyEX7a6KihlQL7EaVo/BzWGZjPda0nDSJEBo9aPDYEOJ2BoFSNgNbSrw05eG+sWPLmJYe0CzNfJfRt98e+yhMHELU4ISvFP5TJLx1oR6Aa69/egeJwKFI1grTIBCIzncnxjWHhN2heE9vo1Qy6OPoKSrv3HytWFPQzHWgUzRvwAXZMkG9u0FdD/Vaq20urwds9Nb//7BNplE5DqBqJOo9F1KIjitwADAIYQxvXuhftBNRj11fK5WzC1Atik1gCGVPNiXDp1S9fKHzDW3Th03aUVdqL7cJNDU5SMfUkXVSeNHY7OURiTLRULI4GPun25/4V6A0Ov0b6VpuyIiB5Vgn8WgCCsStpDNZWyl99OKEObjlrw4/kz3rpXuA8h7wLfttC1IITLoCGMFxnkmRHlAPkdHvxsPIXaLbHDUtY1qvtCvhq8ENL2kM8R4L827rlQvMtR3rOO1gwST449++wBFQ==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-to: udl
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
