---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: citadel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA1b5egV/V3w3Z7bnp4q+UFQUEWbs0F49PAKg1qqsA38BSIwKhfTH7aLjql480SK0tUpZvo/kRgrJ4cE7mBf17QZzm+3RGdBMIDD1O41WmdKb7EwOPcuwMJ/k0Vz4H3XNsFhRGq7M5dQeDkvBclZZdt0rKbOojGrLM63hp330dX66HHS+6PpbqG60DTBf76dW/JxQLqDBJfOgFclSfO4ANtO00Lp8EFIWTjhhCsq5uY2MqBULBvaSSiCpL91TtHeqaLlHNpx1vwgVUqnmR6RioWdnZ4Z8B0bqgEzpT5aqJ7cRG8a5R+gu9QwM4HumFPWqisYvnzRLecJx4a5jY75S9Cv0ebROHiDjQpQWV/Xdw/q8oV889qBV/HKdar19vdw+K5MPK1n/ZykLpDmcq36yBJiJ2J4zr00fqhD2f92IUA8l9680uvnzULmaLG0qEHhzpl5slIX4piWvb+k+qA5kaQ4gd0YoJeE2olhk3x9+npi9akJMosnUXBaJRaCIHNgm1JAkD0nScN+rE+FzqcREkA65usG1zv8dmenv1MtIZWD24uofwwl/3A1as7AghqohYXDVtUHg3JOjXpRpm9PIEgpcPiLxeVv0KIJpJSHAVntcHBy6VbCccOZPe5aZZIu0bVGVRARwZdfATUyLJUSgJcNDJhPfl8mLFEPPyyiXyctJHXzenZ/lcG3aSFYTAb5dsp8zF9gqM=
    POSTGRES_USER: AgB66x51AWnQn6CPa1fOU22zQ+Y6MkeUw/8YQ/znpjQpxzdhn4EOYvYsrIXte5/wLm8YCILd8xVVRqFSg7QZGZLDmvs1rp2An1oLUvxv6un06I9SWvb/9AHRz4CQUlq49ri4gqxnaZ6HTlUND8aXErVPeIFKeuX9TLZuDYz0M4JBmzkeaEH069oTG5dJb6uRcKVb9x9wRqz8/58JG0pQ6fYky6AH5j46DjqC0PsKYmcnQsy+LZxJTx3bmBxBC7JIF7pfSgHnJr6JJM+BJsGjrJ8wAM6BLdFS9aihlVAGrCh4RxvKlX10bwlL9w7PcDhIbYPdp/qdS0DkMgLoBeT9T5KWcf7EbLYYawMiDdRItYOQwXKyp5OBMqQ8UU+eXVPdHJMImyhzvElyr0IEG+xuv/99BAtr+yVPg7KvSgRXm8KJr5lV8PX/BDMsitQ2/bfMp6b6irki4/8LoGDS379/+x2IDzv7e4w2liLF8Kg99Nq/IxqVeUfI72skU0MyZSn8XEJ5aOVOMjhUS1+k/Lx5v7IpbK2XsZL5S8q89c0MEBICB77ASsQ46PwcdUxD8kNPn6YzfhNYl4KZNCLL4DkK6KuM95NmkC0RdnuN2guiKgRf9Pc6a4Ymr53OxcMMXdHRhjt+XgLLIkYVfbQ06GAozfelDM9+aEWQMS6hls7cICEAHnWoaw2NCiy5NK1WbO93ffwgs1ha0lBtKg==
  template:
    metadata:
      annotations:
        replicator.v1.mittwald.de/replicate-to: udl
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: postgres-creds
      namespace: citadel
    type: Opaque
