apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
    annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:Bh1YmkgpSX0fmGamBPVLd2L4xr5cvr0=,iv:/ysIwHG5hcDJTw3R6kzVExZvuk6HPgEYHY9Ooq4F76Y=,tag:38SG7cg8VaOPkBMWAt8D2A==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycEJZd0k1alpHTWoyV242
            QXlaMno3NmxWMi8xYi92RHNSZ2U1TzJHNVFRCkJ5VnRwZW9sb1hOVGdDRmRYRkxS
            VnU5R1FRSlFNV3RBNWFaTmJTalNpNUEKLS0tIDBublFwbWEzVWVaeGFFdFMrYVhX
            Uk1wNjNNakFDZmNIQVRWaWhFRThYcnMKb8j4iv+5/NmNlWculEcBRYfvKUCDAuko
            hvpAx7l6xpSqQljao7tehy6GbzxUUBbJAuAgaUhxN7EP/GCi7LjaIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:37:53Z"
    mac: ENC[AES256_GCM,data:GFjQxLLLRtg53e6J6sqIaH+QbF1xthxFfSBQQI9KcoFCqPobgMCkfGFlVkXQvr8ly1th+q5vFg/dAa7QYkX2g4kFC2Ommm3S4NXdx18EB6mfZ0+y8esNRLR6nAT8q6b1OpDA/w99fXq9/kDcZ4P3ZWlHtuqgIa9AvHvKarfsoT0=,iv:St2WW6RlutPeTa4/hJt/8zZ3T/1hhgpwdgFBfxAiQf8=,tag:aN83Rn3pXUd0anazyZ4fLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
