---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgB+Tt6JZB4PO005/3K5mSz32VjIsf8CBgSka4EsvRU9CaWp0v5tPlWSGMWR0mq3k5A5Vo9NFU2FpRTzuMAMBfo3ea0607aH60pEhS85BnJvx6PrxIaGc0GgWEvoLlepM2+rfp3nu9lhBtZmV5eTR2jOOPYf9KDU89cXWeLsaXueh5Qtf1dEcYti6RS0Kr6hkaOc8o5aG3oN3UNSfbnLlH7awTE5hGTmvQLh7aqeGL87cE6bAkTr9Zre1wjoSfU73j4UqC6MebWJrw8QfcWEjDQ/FnIhgyenvbzuriaeSa4UdgAoymHGa6i72rg8zFmStWwdGxOMNCDXKckp2lMiuKlN6J5H5Lch+DHH7BbAIqgOg2lQ7sBRY5ff63+eg92O3c+Yap50sOfKvZ/fwKTeKev7XfTZw38MLC4t9nwgrtfr/8YDHroe4/gK4KiaaIhod8UFT1FC3vTJVolyLiYig/nOuc05RhRbbX8m1QX/i7jkEcE/VMCTslNcDZY6ab6JKx9DG047yzvooA8Zr3zAhW+32colQVKERP18TfnvNWa4bkSY044m8E9wFOPKYbvXEt2UpEvsBNEmbh/z5/ePfDFAzvURNlze+9HXn908WGC8bQg6zReTxZ8a02L7lJ3Uq+OhIrEVDxEzEFM5cwekIlvnBivHYq61Vr1xLKD9Z8Jg+vXHxf9jV5OGLc794t3uc99HXHV6CAXSFJ7eiMidXw2dTPvaxNI/Yg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
