apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
    annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:8WFADOElVNSYAAl5+G3NaPG2e9l3i6k=,iv:vZX2DDfB09eLyn4zlzK73jDbAh7li5MkU49kJp3Bi8o=,tag:jB5EUnjir/gXQieCmfaang==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT2lIQ1lCbVh6Qzg0cjFj
            UlJHSENIWWlVUzVaKzZWZGFNc2tid1lKSnpzCmlyaWhHQmlLdHJ0cWpHMmYzYkl5
            WHIrQlIrQzVFUkYzUUdNYXV5TW40MkUKLS0tIHBxaURRNnZCbytqTU9tUjJwUlYy
            Z25QaFlPdDhHd1o2OEJqY05EcjRObDQKeEGC++XcktL+kN3CEJ1aWOZEuea21Lxg
            cO8uRbL8XDZXlsV6uLy0LfnMwPK1idN0dCEQUyv4VmoQxN0BQTWcoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T10:04:44Z"
    mac: ENC[AES256_GCM,data:v4TVRsvsS0rL3FoT4t+bHyTz5dWMsLRyElZg1R6VuxJ2x1M0RMXYh4tWbB4xsUfX1GFwCKoJ10Ls1nIaSmxZuwl2uYhPK+xHHY17C0a2SN15b85IAHtc2zCQKU8IJOhjzeHwqVBC6YKOVNPmoeL+hRE4YLzwkbPezk9QqOHL5wo=,iv:V0YYQUSt0NxXOMcQsvgp/ewJODVPeN0IbHfIZ7e6WLI=,tag:YCQbW69bLxjAEG+ahWCwdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
