apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:Qr78mJL+Sl5QxFze6hzzzLZdfdpuygk=,iv:esgdX73v/PNS6nXnfzh5Fc+DOuy3JfofVliKdBc2lag=,tag:W/tL1OcSgxgFl9LSAlbdmQ==,type:str]
    RCON_PASSWORD_SCRIM_TONY_76561198123577596: ENC[AES256_GCM,data:Pa81vSofF31Xq5rCH+Wm6eu1PaqY+Uy7tA==,iv:hVRC8/dxxQJ52hRyK6MeMhufqOaBTMVkEHkXEy3z0l8=,tag:L/2SBRDjGQOLHzA6nNEWrg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV1I3L1pCRTlaNmpqanJX
            VmtQdjA5QlBicE5nMmEwRmRkQmdUZStGRDNzClFuOGp6eDBXWTZqanB0ZXd5Z05a
            UHR0OU4reGZBMlFSdTZnd0JvUGdTNEUKLS0tIG9QY0lJZGl4RGpyZ2F5SjgwWHhG
            REozRjc5Zzh3Wm1NcTBLaytvakZuQ28KSRJM+3EroaWijB74ktnlsTMOphaWCQrY
            Hv6m5MyfxtNIJJXuckv/g4VQMJArrw4ACWJVxtSkeBXC5d0zrtll7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:13:34Z"
    mac: ENC[AES256_GCM,data:Uw3ObFC+LK5ptu3Ncr8T0LbJE7UTmzL9j8WZbCMzS1ubxJ95UWfMtuvg8mO2sMYr5zZFmvZQa/anvrkQcVHRV3DzRR+/1Td4fjaHw5KFz64/zUExHNYU8Nc6M2lMx0F4GVG7XwPd0Y9DY583MAj4nRJWpRr3eaJrQ4boR1hy8Rk=,iv:TYBTrs3fcgLPJ5LHMRsDitEpP3jzjqalG4NfnH4fMXc=,tag:4zFuZbkfcrekSf9pEhmp0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
