apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
    annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:7KhKkBvd97yit3XyCaMZg9YtK0QaRvA=,iv:po9Mr59bp39QZlZ8rnZq0HvBg2JXPZFQ72ooYdxRQqw=,tag:fgw+maQbpdMCrB0+36wc4g==,type:str]
    RCON_PASSWORD_SCRIM_TONY_76561198123577596: ENC[AES256_GCM,data:2ay6zQ69gKEAcqO7HJa7lBrxhY1PvfiKGQ==,iv:diWG62qUh5mTesJB8AccYPODb/oCiq3RvsOf4be7iPw=,tag:n+qTLuVzD2O52P6tWVTLtw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlengzYm83SitsMTcrMzIz
            Q2VYVmZVZVF6dnRTK21oZHZ3K2RkRTVFRkZFCitKQ1dpWUVlaHVHL2J4ckpwbVc3
            aTc0eHRnRXE0NFZ2RHEzeDVJZUN0bncKLS0tIHFJL056ckMyUTdpNnlFb1NMT3dW
            czREMVY2L00rbmZoR2FjSDBXRW9lVkEKIvuK5cQRoQyAH9ErrykiTlb3NacIeZ08
            kF20JT0HQjnCaSaDIzEZRaoBqkQnnnvKT/XxoT2lRy91gYA712Rmcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T19:08:53Z"
    mac: ENC[AES256_GCM,data:1NWNCGUDpLH20IrHomVeZ5/PWW1yjvYUbN7Egm3Nx5xXA6AJYsJVQQ0LZQ5Fka4tb2t/4dU5dHAvuv1aDdwxWNQky3WD3+7R8cAMBt0o9siLkgb120HUZYlttiwtdVQym/tGlBeuGnDISl8NF047h91OhF2uF/24Fb4Tq3ERnQo=,iv:ry4Gl2vXmwI6S99xto4S+m9V8RZXihDFthLM6MRCBF4=,tag:WwYAFz7v+YkX+F8O/y6Dmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
