---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgAmg7ZPChxQk5MdSF3+YW7MhEXd4y6x1xL7rugrTpvR4AIJ+tmwLrjLjxCH+Xk33if4deDDHXz+bx60KuBRLZdeD5YphjmdBWph5DzBA7ywKoXqUq80vq896CJ5a4kk3pBeu/v6fYoS9VZVbEnw91eGa4AOindfOEP4DIYiaRu8SDFlu0HdlN8Sgz62URKF+kfM/POQFU0770cPywbbbTvPczg9+WRc1ekZZ5R5eU3dE18KTobu2G/1WQ3OyPY64DbuDuSQ03TUpN99N2cyK7qFpPVO5oc5o/9nWMJp2KJ2WYSZrb8Q/tqyV7l0uVE/hlQ+T7CD7ft7VLYXYUq5XlOhYLt8J4zBq+C2sr6vAfQpBRMNPy3SvSmQRVg24IrR6jUU4FVyBXY+J9oH9yMC1e/wC1uIfrrcBxI8yZ+WaaN74HBjdBKFyKOphAuGCBsaRkZBPEtdDpNmfZN7ycxjNRh8cQqHQax3GY9EVk+NtuYyw5nwuuu2VKd0gWxndm8+pyfoesKmyQeqbmqRF5DEkNQZc4ctcnM9OW8WgT8e5vv24qG+oDfNIBNeIqLsMV/Qt1RvzyPzdQsvvYvUsZ9y/prNCESyjYPOGHPNz9EbzD+Q5+mAWIG0zDnpG9cDEYM/5jnJPf2IEzhSfKPE3aenZOYgLvNnznhcYF5vnqw6Lb20KWhi3GmlPP8kgY18A/a1z9vFZu5EZ6pcaA6uoxdjzmL4eydJNie4fQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
