---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgCDW0SakzKdV+9TQJ/C/VPannuzpDXAOyWuO4G9+Wpg5hTNmEk6apj7y0zMqZsUA0bl6RGlROotTPxNShL76Ap0d1smaYAIVRMBQC/lSu1Dh6iHhClbyy/1EQfiqlUswVXdlFSPWypePnl9De5+tvSEI/AF43eg3n7tjsEBZ6rXBWq5qPUXiMGsIvvgI1GfQkQkKWtambjDbJuv2J58GAh3xETcjcxCfgfQs01HDlOJZlsoUJbjnY8BCf1VBvP0NHtTgmWwIaEbcWm1mM26O3DsdsUbX1XDuXMNvBBdOQTd+2+v+7lbnuI+vt3svA8XBljJiKanwqJVkc3bTsSYXnRh59JuIkuDJyqpP/Cbb5VQMV7Xz/wQfSx9ntiTb7ePMAjVMxu+Nx6KFv5vssvadKk397Sjkc14GBPCVZO4xGrV17A2K/zFZr7zcFXzWX7vKgpIIfBQwlHR9oKX8R451M3Jrkp1dZzJTOpkXMWXwJYFeo6Mt3QiwDjhELTaKeBe0k6hhyandQ1IgcbrvEJjg7rTkfVzPD8Ux7ydBlkHfLVGkCgqsnAY9EKDVSfV8MkrDAC8f0XN09GVBg2dMaOQLm/BlCu9Eo+S5GNSkE6OlH8mXmoMGOsMq/gKSvr3l7BYsYYTEiQ36jbrMXKN8kpHOVjQsIZA3J5rNBbnPxATWz3ZcHfcqgUpmr6r22WfC5dWxesHHMU4mv4+EH/mIFS5S2x/XPsepyK5fA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
