---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steam-api
  namespace: udl
spec:
  encryptedData:
    ANALYSER_API_SECRET: AgCEADqjXLZ5wcTjsqMZxvYDjslwq27M8hhS2wFWoZssvRkL+6c64hPPFNq1xOi87Mn4Izj1LiRonF6l/BDC0Yn7eoak0GQUfcoDK6TwnyAixMtIRjkjgueraK/tAi7sFKjXL0gXvXfqCROEqUeRooovuFl1ArEotmhy4Ww7qhvyfB22xJVIfedRsnLBpg6AS7BhOAxfO4N1phEF6WOJgqfqZeZ1/NPDWjFNW+aMBkUV1el7ph4Us7lt5OwjKCLsc8Y+GK3crwpfsM+mrLEDaLBxPynTaAA/G+M2HzKgFaTAWw6LaGKPJrmRXwolqkkZdz/2NgCMMF+8ehfh70m45ObjKHcwQgM+XCXFIlXSqokGDbkG+c106XEDk8QHRTVd2Vtx6nBtsoMe0dEXTKmqKsCdJwWK4qHoS1MHyMEHz0CDORJ6KND+9VEYP3ZBlaHLJkd7srhkeZCF204kQVLoeW3dsYdlzY7Zj4zoPg27H+d90nO2fFLnEkGSvG+RwVFYz6+f37CTNJBpFU4YkvOf+i7Hu3iU2uUpGy+d1JIT6ctYtGRyB5tQJAU2YEFzJN9impGMRQRgN7YyZAUoHmSKKXAS9rj/TWcDH/y0IVRXVSrNnXjETcUl+KbP7820HjamqR82PlYMtGSWrkjEUsu0v0pm9LgeGkipnn3Jmt2dFk5LpZ5UwAlxavvUNCxqwjz1ioeFRk4C/JzEna3Y9oiuK5Y8UZ/IMdhtZ/Ko
    STEAM_WEB_API_KEY: AgCatZs3E75KCwCSpD9qGJknV/w9fCGSj2a8yYPRD2QXj2zPHb3fq/5V3TDb19ab+oqCxq9394iWDyfqKw7LodnZh3UZJE9jlfvYUboLE6LUb3enNmOasXFN25ksFvc4vzdJTiKTK9e4lSMRR3dAoADzdjkV/6txHr3onsadQpywxasG0Od3zEA13MH5eZlst1bLvIIPFRdggx8PQCg18ig8t0E1XNz68q6/0jnjCmaoO2nfA80CNqVnIXLwVgD9tyrI2xMsaIUxQVwOhob83P3bDd2uLCivn4kXrW75xl3tzwkSBHGsKR186epsLxSxmCxjw9IRJVskJQg3jFt50zeW/iePzJDUdouNSJ9FBTNHKy6hYTpHQTzUWPMKGd4M1kr3uSUxja80LYpX+TAwIJAU7ivyNoEjSPT6CySFXigul3C0GNtZz4HD86ISw5H6UTFQTPrvNqJlKGwLUP1UxAxYrGeq8R4vq7bur/jqxFRtN8sFBZcN+sy7X0bBPYoat3ye2iYzuJYymQBr2Qr14J1cptT0N1K6tYNme+dVvAZBkUW9Lx9OXPLp/J/5p8kuT3SwMX+7++8lvd4NmeAoYU6vMcq5RTgJ1hwO+kUwN3a/NBI1LEdK3ICCuE886kOwFnGarpYemJ3z3/obC9rlR7P6Ahyjgrdm+z7qYgfvYe03ns2RGANjcO/tTMjT/USul18yTZ2i9H3427N6F7Cv7VEhi0mX/lP55WWo73/5Mt9jgg==
  template:
    metadata:
      creationTimestamp: null
      name: steam-api
      namespace: udl
    type: Opaque
