---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: udl-stats
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCAYTrN8025rWkm780PrCsAIkPdkfyFAknEzPz4pNrveBftvyMnoIdneiIRD+473i1c3JlsiOqUizDsaDWK94SvgciHBg1d1/3Z5qJyR3RwM/PrBHDKBHnCNOtz5yKAF8iqh8gf67A5xxVSB3bj+K1/rTJNoLtG+0d//jWEvgrRsqTlEjf9k0VYwDXenqKLGhqkPSWHJuv7NG4nN1CUWHe5BVV/ObTdRjigCpeG+NTTpXqrkWQlw5jkIbW+lZQl6hu56H69gmGZaFeg1Qo2pknfVtsn58VB/kHpmT5YFa7+jkxsgK/D8riWNpCddBmPaaA5Yt1zWV+VpyCoey8VsJLUh7jIpmat1Mh7GZbf2khNOkItDkgx2kaBmFpDw7zcW2gIZgtoxvyrKFaSDL4NCuP5OMzKhH1YXkKtSiVWEzGqQVlfFLKA8uYRNDIv3Khp25e2C8ewVgf6oqsQOrV0jtsCP7R96S3pFzUuWxtPu4cQbg9Z1EDPuyYYzdvHjJ6WPe64HfvrkYqc3rOnIzGxE5HDPqMPlpGTnZYM7b8vKTPr6pdSmihf9mEZj1GfIu5cHG5WyrnSr2YVi7Fnf1bfI2WPxua+mHZgVnM9sssoKfND6DxewEIENbDGCnt3zpYfcFCcst0oZoy+kdg36Eu3T7axE9P8K7pOdHI6t2dqoAcUwG1GpVXZBa1vvP51S7UXiFVo3CsrwGpFwA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: udl-stats
    type: Opaque
