apiVersion: v1
kind: Secret
metadata:
    name: webapp-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:kPYDMZS+c+uEZ1s/M2/cGA==,iv:GwvjUn6OgXHLanzkAEnPQOKGJcwn9bYWFSo8/nUII/0=,tag:yoHrUeE3W2NEdoeyOZiwcQ==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:6QlzZdHSZgWQB7xvGHu6JteD8yAizqWrcg==,iv:glNQhGf+WruJg9YmQ+twkHV1c4NJg47J5EgcY9PxP5Q=,tag:CGL56nkJecHphAbNlfpBFg==,type:str]
    #ENC[AES256_GCM,data:TwrXzLxffaLa9MURw/Rz4BksWOugN8Q=,iv:fYtPHPtpsypZq2TD+GM2gKP5yI5eZdyxTNTqAGc5cxk=,tag:LjHNvTm7UfPWp3fAs6j/Vg==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:GjevH0VnlcjvzubhbRsTa5YYqJPPQHYzoGu2HJNcHoM=,iv:S9fmfqkcspKlT3C/ckcCLMGHxcobSzK3ZoIiY7YcDVQ=,tag:hOPm/9AwmQzIQOgXVazvdw==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NWxaUlN2ajlFQnIxNGNk
            cmxaeFlvclZRMXIxc0dWeUkzSkZWYWdYNVc0Ck1heHJ2cTJtNHROazFGSmtRaElt
            bkkrRHlqOFhjZnUvdUdTc3pvbUZhbVkKLS0tIFVSQ3Ayc3k1bkZna0N2bUVndlNZ
            ZUNidzNXQlMvQnNFODllN0hhRmtsL2cKSBQNwT2uJDHu/LSQ2WWg6yWw6bOmPcEA
            DfCFJjeOoC6PLcQ3hSvlRs/UnA/SBa9HHAKXDXTnwXgC7GCwK5kvEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:12:59Z"
    mac: ENC[AES256_GCM,data:e1cWLp0fr9l88QFuvy/+ePQZhTiXkWcWfdjOVdBsX9eE0KbVxVr4CYive6ZkeVt/Hp+s/+H6ZZ3N3eQKBnO2iK1Z7dBPR+t2x2kAcvGIM7nhd7IO84mwhn4pcTQKJa85SwnUPfBgdiQ5bxBE8+7nhXM+AJBTBzcFPqDXVB6fFvU=,iv:ShXwAPUylo/ZuIQn14fvqBsQRe+cuDEpx0xKwXalxWo=,tag:+aTTMlkQCdjPtEOD+9wXmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
