apiVersion: v1
kind: Secret
metadata:
    name: webapp-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gpThJI+9Ga6tba4ndoyQjA==,iv:JZTTp5S8deHZtRcqJ2a8L003RNOSWRxvhIlw6OWoQEU=,tag:0/kPvo0Iyt1NsDCmdztJ8A==,type:comment]
    ANALYSER_API_SECRET: ENC[AES256_GCM,data:soPfi3MYfIiC8l1jfkriSzBCfc7TJK853g==,iv:BifxDUdx4FvTMAsEYIAwDXJ5tyg8KddvX7KBAcD/Nfw=,tag:bFS14sPBQXTNxIPmTXAC5w==,type:str]
    #ENC[AES256_GCM,data:7ax2WjwdPxgll+7ZPFuvGzafR6/B130=,iv:Lr9w3OXgza0ZWL8dLRrr7vgysQ1VqaeONKUPP1MFIng=,tag:5sfvpPEySOq+Ym5+t44PJw==,type:comment]
    STEAM_WEB_API_KEY: ENC[AES256_GCM,data:bk3llby+S+/x6eCpg4fQRBEcIxwphDjlhI1hCdS/g1Y=,iv:78BcRoyAZjHni+T5scQ9uS6WNydY8KW0qGDrMZ3mkI0=,tag:Y67L4K495Mj4YXeXUjfigg==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUWFPNzYvRnd4QU4zYUVH
            eWs5b0lIcUJIWGdnR2VNY3ltWitvVktJbjFFCkIvRlJsYzJ1TUNrUzB3MkpYQ3dQ
            QVU2cVN5eXArMzVSUUwwNWRxVmVNMlEKLS0tIHRBaHB2RHRoTURtSEcwM0pFNUVU
            QXlvY1ZlUDBLbklEMjlKWCtOT2s3clkK8mPwrgHl8PYtAvbZiapC9f68lrreLPfw
            aEJTCrR+EHuvo4XHMsCn2BVqEgnbM6issA61SUsAexWs0+JG/C1zvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:13:34Z"
    mac: ENC[AES256_GCM,data:ANTKZNk0bRzhNTcd+kLNfHytF+XXHKfWhkoqkIay+gq/OmA6BSF30me8jOg8fjDN40H6hXVoNaG47V6MDCCHygpTR/9wv2Ljh0cmNq2ASMUHNJssI2Cp6HGk1fIpA04poX8WzHWBdhklxhQO4rNO9QxtG5B3K6QCK2BwmboIM98=,iv:Y9ay+4mHtv92tFze/LbJYY6CAMP8CFF9VU686NUMgEE=,tag:D4uzBE6GckSNEO+AV2YcMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
