---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webapp-secrets
  namespace: udl-stats
spec:
  encryptedData:
    ANALYSER_API_SECRET: AgBDkaz3JIxyNiv6LdDWhJW2BrXJtCSGMtHit5W8GIsqJlqne4EcEvTd6vzHf+EMkZ4iXyv37uFDUe8ICJZi0JPWCHpmY+JehqjeGOX4uHsZMAC2wrIjNlKcWfNxoa0ncI7iYNi1cwSNs91IElFjObwPXvP3W8eSS2aGWbXK3kwPuElkjaAM+tdFJjGgAjtcgKSOYJrHvy+iLIj09WI1vZh4fo1rn5AKc7QFdHf3PhALjzIlj3qQEkLL3QoorByuSgkIw8k91JcHg7Mqmn5fKVePT7t1JYbjVjH+pKCHncrYzZrTU0LNa/EcXk5xuRCJegaO23aa/hCycV1g/meisanELNQToKndrcliRu1C7GRNJW7a3TKRZF08Wx+wngC1Dt8XtVyiEAF9zu12qXhNuJZCQiebYD/qYd+CTo/7lBwNIYQc1wzGs5x+RLfYIGPPO1G46UlhHvl264R3YKJzPrHQv+plVIymYfmiQ3hBFNXu9Z6bYLqXqY14gTsi+dp3SZ2T346lRjfC5IY4sJzEOh8PU+DpTBVQJEC0yXHcIGYYJHLRsquF/ZzH0T2t0xQFGJh8D8A/jlf/eeKn9MyOn4WRvgTF82WxmTSk36tmqrt+GfUZk3nivyQpG78+DChctiQ+eeZjvU4EK72qBvP4SFZiYYrjFB2iMdGSGX2xZJlSHxMco2f9f88jWHbTase7f1jOKQjbZt6m1lyYcJMwCQEr/lc0IU0N8o6O
    STEAM_WEB_API_KEY: AgBNLy2Ua+EhbgY7ZSGctHjNSxSDcLCEP0xNt/jw0TxMm+O5yFbQgVjHgFpYgNFKdWM4zHugNfCl25hmPYpdUlAJyyuvOVIuiHwIYWWIt9RiS8RjZojxON9Tb6eqe8ahAOq3UYBSe8oyqfL6b6ZUgfX0pU+8jAtyRs1/n7XPpVBdMh5s5PD6Jy9Z0b/vhUqNufAj0q9X8kZGAwzyB/NaDs5Dexo4Pzof8c6ejApACqvtx253v4mqXOiw/7m3iIUOWRkc2YzjRRsQIhAlvwtPbaf2zWapAw2h3mR3ka38ohzgWQ7EpG230QVECCVj9ZcLUxWVknV/YKzYqtcFQxODek2AYGUMvKds3iGLRHQBTkf1BdsvU65Lg1is0Crz5Pgvnv64CLHftgqyXuxpuxVu6fpNzAgAJyzARIDoVL0sVyQLifQnKvR/r79294gz5OYFV5IbCHSpk6KYBZ9UAaOuKACCDmY+r7Sf5TsUvo2sZFG/TqUcyFHYkE6LEvVqm4CQd/lsMttxOHRWRUrBEeMeZxxelHzApR9ugmcW+/xs3WjlMy3areE6fwnaWkrORC71EPKMEfQqIfHQ8wfld46t6KrFoLbnTKelUZ8Q50hDdRzkEnS22rXDIKlye+wasNuSBQErMAbyDvQtJBK77bp5+yBv8aJAOyw3cQLFIlL/BBtjvsaJ91g8gH5rCXTzBsNsViAjq64NnlnhWu34ZfbeXz4XS06dgaWpH3ebMssPTX77jQ==
  template:
    metadata:
      creationTimestamp: null
      name: webapp-secrets
      namespace: udl-stats
    type: Opaque
