---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webapp-secrets
  namespace: udl-stats
spec:
  encryptedData:
    ANALYSER_API_SECRET: AgCj3Xp7LKmVgkJOwQhLFAe4gthkFEnMc2O2RFQKeTH5+LuK8ssaDe2eEOwd9A/lxcN/ENM/OU8JKI+arH1udIejyKr5mCPGj8/qAoWrYMBVFgECPBekjldf0rI7bqT/krqsRbH4lCuw8e3BvD7OPmM76TNEnEzA/s7edefqlWluKm/eYbB8YBRy54/h1KNvcKVauw6YEUxnKQjFg1pYlCbvvEZZlMUpxS80aALoFjxekVTT69s+ieUL1RDcNtQAVbggMYsE77BVWy+AmAxf7gxvisu3m7O/yahZ3zqnJbAQ+gVk8iPZ5nMl9B86zolZO0AxxwPaR8CIElzOsRrpwHIwKoTYtuoaXys8uYI+DKWyM0mFbhQXqXvl18mLja0RteZCkwvZp9bHgSow4saAFo0PAV89rY2EQfVB+q3aDHhIW1SxU5gbHXroq8IFO+XQAZvjVH1+Vr2MHz7yXczqhmF251SrKkA2kF3/jrDWfCmzoLPteWzUp4E7kuCKch87kstEJpbig9Pqs1orX2P+dlzInzqt9JCwY4Jr3dut4LpSE7ZZmPtsILwl3nbWDa/HHpEEicIEfDHiAVBX+FqtswlI5hXGbqZCwmmVBisoGii6N8HtVK48Y350RXxVG8LYlxES+W9vRLjireZk4mSh0wX4syVfZFaDWZeNoKgpE9OUHrBm20S0r/7TJ1cTC/Y7XDxS5yZMjY6libD3SjdgpKkGdnbWLRx4P9O4
    STEAM_WEB_API_KEY: AgBnRDmL8LATA39cv88K+wFCCxPS+CF9pbBfnAh3nM0u/wHKi6Xi57o+Nuj2zoVZrp27LuPsq1AKMHoNH0LX8btSPogT9DJFNbxtd2XOAs1znWj22S7DM/hbhna2d5zwmClgsBwqxN+MYUHdpZvqEiz/jM+g92th32QyK55I4xa0RdsrDfR7V8965Kfe7Ifx5FFIXiEtT/tBu5KGPmncY8x5YB3WT6zx6D95eFpqqkUV/uzPlUX0xOzOXLJVHc707gZQP2gqclzrT08GQ2k+nehB3/4v/Y3oyhUVsjp9hrSSu6eyX+HtNDMrWF3NCNSv5T8DuK9K0b9dpiulG/F0FolfkO6Mjfiqkbu1iESeqqpwyy2e3bloHvosFRsK1ZvWWmZbOKkmm+u8IXrwzZ6i2awBzLTlYCte9NyPqB4e/LJLpZY2z+I/5gE2d5kT5tKwx3LVuf5yxXNUmHtNP7317r3tfGIvK05XklogmTREq3o9AuRk6FpZhH5Uou0wn2fEBE3Fh68CIekBybeH/plnSJSfh7WLslL4f89l3dORLDoyWN8jj8h9UJ1cEM1Q7MGir1Vlpk18BjeMxxJcJ7z9u0sukJuT6x/N8utPMYm3idc/vE5dnB5DX7LsizD+ZyvyH8BWF9dppowDWzUv8lfE2EZRbuxrdUw3kIpzgkMzeY/Ix6dZPJaGkjBLjCY6HqhANgpxRdvcwDmBFjpV5CL2EWHeIU9PcxXYcBfCVlLXYX0TAw==
  template:
    metadata:
      creationTimestamp: null
      name: webapp-secrets
      namespace: udl-stats
    type: Opaque
