apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: udl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/udl-tf/united-api
        imagePullPolicy: Always
        ports:
        - containerPort: 5823
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DB_HOST
          value: "postgres.citadel.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          value: "citadel_prod"
        - name: DEMO_PATH
          value: "/tf/udl/tf/demos"
        - name: ENVIRONMENT
          value: production
        - name: DEBUG
          value: false
        volumeMounts:
        - name: demo-volume
          mountPath: /tf/udl/tf/demos
      volumes:
      - name: demo-volume
        hostPath:
          path: /tf/udl/tf/demos
          type: Directory