---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgBatJ1PUO98kuFcTk/uw9LHQaSQsheqG/jIuqBou/rSKCXVlgxpbOOGKNt9cioD8CKbAnmvQeyrNVkButvZFsn7Hnj06x2L+Ssf8fo9PjFpX/kZMDyfLipMAX52Lfx0DFkIEQpyzr4SYxAacxozkSFT4Y9VKbrLPNwnp2ZAdKl9cy3cz9sCDh30uP0rI3dh1WHDtBqY9pXmT8A2Q3pfHmOPNQjgSDHCPycAok+LBdPvg7V76gPmq9mQidOnHFF0scry5q15Klgg0jWKTjg8Mnxj2joz1NRXyTn3H9XdF8R+V6sztZ+IhAORekRONsSB1D+Z8C7xH8DoodBJ/ODCCNOEKPuxNosU1ktnGrwcZeyq9uXjLSPBThiiJ0E2Iqe3oaVX1qKRhFQQyXlWamr9mj6XUPlswdcYbn37gXRe6oqIe+4PfKsrhr9D3Lffo5OQvL421roNUzSlnTaoyvARfj9RvN/GcTRegwPDPbp/2Uxa5a1NUhD9M7/l89U0umU64AtfGJa8d8pX2TEWF2CK1FZK66Qxw3ZagepUVh1wlba8SK0oqQ7msBmRvmNjXo0OuIYIu4fJbvLHVEnceVlcb6LvHK3Ae3BqaQqVARwnx2rIGpGqgZEiiz8tVETEUPkoxvjy49aAbEopCVr6mEz27WvrTQGWEiOLORdK8W4YcboX202QhWD3Rwil065YIIFDbHJA95GAVvAxE4byEbbwY9ZuhHJPrKD8cA==
  template:
    metadata:
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
