---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgBt2LayiH/q5Q8IIEqD9gL9owNfEiXkxGKYzZOUfyefhId1etuUzJJs1VZAg/qMXBOEvEWzeMEF1pSLKuOe7yv3f1r/E7oyWU7p4MHIpY/zDb5QgvSIU/fYqy/sGhQkkv1masR+oC8l5Vj2zF3ak21g2nk4LeCYrrFtoDjr3aZU1nJwJnZr1sPErUrjWr/ItKcH78e44uh1Wqu5B5RyReDQ/cGE4rv7/VG6Z+Qxnb6xFBMyPLCPXWM/fn1+T6aoyoiPGFAmLv8NIb2VjUsFd9BzbC0rC4mtowYXs+VKLRTMnkFbO6l54vr0K98nj3/P2qmQr2liDJSJ3GuuOqljJLDjv24YFBO3HT9tmtTwAsQqwLL7S/mdr4sfavAL1QE7x/RMPplIHAlnotQPHFsi7TPUspXDdVo66k7kSs+y4JnsLRchbcG10PJWwK/W+WZaMqjmFaDwwh7bM/vr6FO4J+c9ME9B1/LI5PCTXUBRdnmtwb3m8lZw1irSUs8sZ+xK+XscmIpcyrgQjO6i+/vxbMW7HimsXJuiuRUeF/djASAKms0JLU6mpU5SbOX2dG9bmX6S8rQaIFX8c/GTZDwcoaY31Ayz9GtGse4dLkcswfDXuPypvC3J3TqyQvkjjgNG3rw3i/zAN/oAGg2uI6giC3dk7sT+CpUw1/1uD3kARhz5TvE0AizJvDS8yQhra4b28fnx8PhcleT1Xjn4OsH2fgoYcx1pP7X+Wg==
  template:
    metadata:
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
