---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgCntf54I05xEmAdxQYoR47AIjX7oURs8kD2LmngfRfrrNOFbIWBtWo900WmQWASAXFkW4olQpkiaSPhmyaetAcpLkVmdbw9PJ2Cprh+XQpoKQM0vY+l4jKyT5S1h5Pk2FQzsRsrjxDW/Wk/JLD1cTaNlz7Z8tGTumq3JsEft/pdRgC/7I16F1A9nHUJ1V3ehQir+/bOTsI3ICYGvn7cuGVVeUoRfWBqHs1QMIq2T+7oYFGtjOnolpHJOZhYT5BTuE0e4PxkSyhiDlFt9uP0m3zwS2ZqEClgAWrWt51xybdjcJBWp5xm+o/9mRVUkv2th0A6u6MR7rxYF2KrS0Wjaw1A9WkHOV5barUJbEnLAAwUbpDHvBAb7gDRy2bWNZy7mAtIycUiIY0xs/70hWH8SI/snXgXBAbJChJ26V1g4t6FFVDzWniDQZXTNQL4/9MPRE+4x77Melcyw2jVd8IYpslHZil7SVeE061xiMATTkKJxkIfCMdEZy32ZRKHxddb7VRrEYOcKgLWIZdOfzvZtalh/Z534n/ZLjT5ghRix1tXWxoekqynPSFmH/DzSQQuuABRi3uUDHASHI/CCj2VEg9iIy69u9v7ARnOTEOWzTo8pEtnoaHO/4CiRnfvFxouhW0nJSg3HfszlD9OaxwCmbbIG2cxMd5jg8CBLhSk/wcQ7lq9Lt5MArrzSvLQcQIVl94Io31FLTVxzQHuokaygGl1E8wH0bCqXQ==
  template:
    metadata:
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
