apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rcon-password
    namespace: udl
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:8MS3UtKWiswuByfCm/kVGq3XM7kmFH8=,iv:GFxxEnjboamQqp5jMga0VpgmSGHZF3c0X0xVwk5aqEU=,tag:kEMW4pUGr43tjW1LmePlfA==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvb2pVdGJuTFM3bGJNWjRa
            ODlMMEFaRWthbHY3YTMzTjZ2VDRYc1FndEg0CkovR00xMHNISmZwNGprTTRRanVj
            dXQrdjAwYnpzRTNESit1bHRpZStxSGMKLS0tIE80SzJHZXZSUDJLcTBnMVlrU09U
            eFhYamt4blBndFluMVlWck9WcjFJUkUK+bjDdAxbiaTiCdXRocG1aid+l/A1wpm6
            SCt24JQcMhAW8nhSlNVUXx5uxBsSQ2nQPc2R99rcBtAGMhf7V8HHSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:13:34Z"
    mac: ENC[AES256_GCM,data:E0S7I56vcr4IFrGQ+e4yyW9RSh0D7sr1No/X+Zmm7HVggnQ3sVs+W46N2XkjY2TniR/DcVb4ruQ0vihlQwfBckGILHvtSR6DXGCDApF9/Yde4B5dNu17mf8uKLY6yK6LtKFruMKnVw6A0gKPPYQc7X4mrJadoQljN7DqhUH9gKA=,iv:5vNjTYVeqlOycImWBk3PeKYRpIZfj4mt6W439NCwxjo=,tag:J7EAUnBzPAHYgspYYfm7fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
