---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rcon-password
  namespace: udl
spec:
  encryptedData:
    RCON_PASSWORD: AgBJEmCQaN5GFkJaRpDxU+CcME2fbb0PefG/WiO35mb9uQ1wrwJLgmVXXMJUV7yAFfOdjkTKOZOJmCBG0MwCv+ZLoM75NgK/UntlN8NE0bTobdVDon5B/mvhQa8rfqudpsbQTTLWkfSzF5p4IWrzadbaNQRqmSBlnFS442poHKZX/7eP9vrIkj83jrpev7Zkgfwpc5Lr4Iqx7IMEs029nDtE6mr+cz7JmjbXWLS79GvNFbLmwDJ1pti4G+aGxrJH2+13MU3qZQet55QKKN0rvqUJSfBsLAwL5B621x6dsIh82yJ94i8+7b1uk5Vx+Z/xrhMyzzl4sI3EIv1d87U4faAf1PCXveCpk8iei2FggSxtGoG1VZu+rn5vDjH/rd//+WRz/q1iiu9S++k+6iHpA3YC8bc/cVoasXSU4DMhcFcMk8LNllLWnSsEpffrJxiWcZIk7Y34JD4CnqHSlYEm/oR9k+3dw8fbnuQwtzvX6sX+Oq+/B3kY1JvmqRbgFtNkE2NgRxBir1aMZwO47jsDMOuhP/QZx3ZRgRe7Mpq+KWfLWBlI1X5E690sn5HNGWR4j6M+svgs9hbPwDWuo5VEBFwkrYSjKrlokFaXjlgfkXVNbByZ5ck2AB9780+S9TZ6gbCwNzBJLSk5vRtPSMiAaRnEJpebHf6bBpBKzTKLumA1u5wOSXy5Zzb9TmmifFA6pFIboFFzkz5/vGgPbO6RD2Lzey1G0LLcQQ==
  template:
    metadata:
      creationTimestamp: null
      name: rcon-password
      namespace: udl
    type: Opaque
