apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-stats
  namespace: udl-stats
spec:
  secretName: api-stats-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.stats.udl.tf
