apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: udl-stats
type: Opaque
stringData:
    #ENC[AES256_GCM,data:laGlZLYCB9c4IhM7apBsCQ==,iv:rxPpH8zQCJMa6YtYnktqBaAeRKR43K11L4do5SIM1F0=,tag:7c7g69Rene6B9Q2OEUEpTA==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:kWEYsVi/zVkm6OsYhS9mnYyrihhamlNKqj44Ez4M+NG2OzZUTJb+vKdtEPheW1HiG1di7geWhR8k/aHnAiTp+NeiVOPCHjpW/ieOFKLN+Y+C,iv:YNMRnuQEGK334w8W4BlRHXaYs8eUfeJdvphVOafLQBw=,tag:U6lDVGPn3mENtU24cWFlqA==,type:str]
    #ENC[AES256_GCM,data:UKHqIuNQNf/r65DcXYSxYw==,iv:DX1ssdtDc+ZTbsI/qcZNpPVWfaODCJXOWNu7JguK/WI=,tag:JuDrvJ3aecONDEKkEBglyA==,type:comment]
    TFDB_API_SECRET: ENC[AES256_GCM,data:ylgSDxvJwpjjcXPkEMGLGfc6s/s0c51ZvA==,iv:Xgj6hZ6zr4YXaF3/SeKvOaL17zb0b1ZA88ytsjnynek=,tag:IlJbVvwxMSyjqY8rhwMTmA==,type:str]
    #ENC[AES256_GCM,data:UEMXBe8ij0/VcBoIFXjxO9MQqQuCJJYU34urcQ==,iv:Y95Pvo+7EOZwX8yLLacUqoDpuecDhLxQXyjDm9iONLE=,tag:6OyEYoH3bq8XTo2391SRWQ==,type:comment]
    TFDB_API_SECRETS: ""
    #ENC[AES256_GCM,data:P2h2MEYqmD1P,iv:CjrMAFpkwuT4waQ/t48azXEOW16JtBCErc2RpN4PmwU=,tag:P2bFSIM8HslXgdbhK0xblw==,type:comment]
    TFDB_MAX_BODY_BYTES: ENC[AES256_GCM,data:DN+WzcOMug==,iv:d0SiD7Wz321Z37rlWg1XLjx566e/uMy3+gITfRP1dAM=,tag:KL+5LXzWYC0xSWwePNyLzA==,type:str]
    #ENC[AES256_GCM,data:SCYiQJKqYPZj,iv:VwIl0qHZqKhopVPV6sHUvzwIkvc3KYk1Z7doa0Qsz08=,tag:crzyfgc1zoJOG2FVInPHVA==,type:comment]
    TFDB_LOG_SECRET: ENC[AES256_GCM,data:WSqaXsCZEaSPNj1ch8msoK/w1ptgtzLVEw==,iv:e8HjQyP6waseT2PVJliS1X4L1OepTahCruB/8bNp2ho=,tag:c61/WJ0cCeQart6gFx8AZQ==,type:str]
    #ENC[AES256_GCM,data:zlhXZecBR7yY,iv:qihfaHE3UC2pcMPnDhhoZnag4OpnNfMqWcNfRcnpinw=,tag:UXQvlz7TDxvYnYN3ZyRsYA==,type:comment]
    TFDB_UDP_PORT: ENC[AES256_GCM,data:P4p0O9Y=,iv:l6PURvO0CAFAN5eppOFJMY+3EvgkO7vofXL57x1lolI=,tag:sLZlEu0Hr4zz5A0D0OjiyQ==,type:str]
    #ENC[AES256_GCM,data:2L5s3njPOno4,iv:J2fKu7sb3/Zesun187RPg9NY5G0YpgqETb1oYqqc7I4=,tag:GPS9CazRgR2Lhy35d38ypQ==,type:comment]
    TFDB_LOG_DEBUG: ENC[AES256_GCM,data:MotgqyY=,iv:J84/f4N1TCYUq2hT368Vso7ynnaYmdssByYsc2fQYnw=,tag:UOdtl0RaWGgYOr8COMFm4Q==,type:str]
sops:
    age:
        - recipient: age1ck89m855d05rfv8dn2m6uf7htuqth9rhzw6glnz3k7mhhnfghf6qnkughe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU3lnKytNQ2pKa0NZSnBr
            dGtmMXVLc1YvQXZUQXUyWmlGT3dlZUU0eGo0ClBIaGl1ZHRKZ0RXWGxSRVVRREtv
            MnVnQjlOU1dBY1V0eWRSR05ySit0MVkKLS0tIGZPOVNxV3FkY3pBcnF2VU0yUnlJ
            d0l1ckZMOWtmbGV3cmZPYlVUblRDblEKDKdv9Ehubq/7pTAr/NYRTOytaujwa0I+
            rL5mizmPbb/HZbFshRd6RnHhUU86TUSfS42zzKsu3Ub6pcecHdV12w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:13:34Z"
    mac: ENC[AES256_GCM,data:nGTii73V94uaHtMM+ui+tpoIA1bv1p944kBZ7GejmJHCq79exx6rHL+Od+PjBEgvbsRgJYK0EGnt4r5xMjp9JgjRxMmJQUT4Wf/5GCBzt73m20HNRg1CFES5Iw+eds98xHEq8x+05z/SqckZgmS3/YtWtB2BTYHgZFop8JtvVvY=,iv:5lZ+E9RPVovLZKuQHI71AgRkBh5MCMvKCciTu1KAnhA=,tag:8mrEkOSGlYU8Fmlx5dW7mQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
