apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-data
  namespace: factorio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
