apiVersion: v1
kind: Service
metadata:
  name: factorio
  namespace: factorio
spec:
  type: LoadBalancer
  selector:
    app: factorio
  ports:
  - name: game
    port: 31456
    targetPort: 31456
    protocol: UDP
  - name: rcon
    port: 26892
    targetPort: 26892
    protocol: TCP
