---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-passwords
  namespace: udl
spec:
  encryptedData:
    TONY_76561198123577596: AgBW1hRAPF304Wk2Ysg+o3x/ZQrhB+C6NaTTCEkmekyAgdwg8sRCWQoJHp4KSaTRH8SIND3aJMLA6ASrKRPOqvz2SF25Y7JUECwTHycf0k/6AYbcABQLW5tYaSdPk/mJezZzQjK7S7ZCIUMl7IZHf92bNSgj/JvrbltpgVUvwKaQFHgXJEH4pXUMdex//3tNrgi3QVFfOg7n6UEqmsyXEBR+pAyglb7I32xK0lGOwXY97F4YyGOLOhTNaVfP+sdkACo6KPDMYrKfVZAcd+ABt7tK7trcVuSW2VrBzqqRgyrQSeMcGpSVxaJFKgujKrKQdW0S68FG4zIP0+tViDLqkb4AHEDOdHTo8B9y5wwDS/8h8lrLaB3HZIZ1Mvko95oqDB1WzVWGTYm8Z04/iGFOGLeZstODOsG/NCMHBLBJP4BfmcTPM/DlSaPtijXI0w5vNSbbSLeMp+fBYtTaK9IcZTdAL/1G/XG0DGSibqtXdEOy0zvCeuW0Eak2tjvzAoNxjF6qT7urYXKtAOVKCEv/fB28xevxP1E6d73pfG8/nFNEBUTzGALwHHs6s0OsGapb8+RvvJpZ9HJf+XOVq8UNsrsaqmd4WtMbkZO9oj7cr5pJcrqnazoB3HzngpZb+4/YnHFnoG3bREOHbz1DjY3kyTD6SzcyWUMsP+cFPmAbzu0hRHxGNnSl10PChUYd/DBZnXzfh4f9DZc=
  template:
    metadata:
      creationTimestamp: null
      name: server-passwords
      namespace: udl
    type: Opaque
