---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-passwords
  namespace: udl
spec:
  encryptedData:
    TONY_76561198123577596: AgCcjZsHT5al68xqycQO1dPv3j1e9yQFRLoLLHs/M3X0/gLen1wXDA2jWaT+6sINWRL3mK6D+BOKesUl0c8gYNJAy5lgimJZSKBfB2il+VXU6MAWMfzZKGS0Z4wBEgrBf4IUDb3HjuiokPTFBGOfIGUEYVQg9e4jY/HTWafBE6xc9R46J9XBfcR40xHKpZ/d5jQJUyt3rbNFIHCoJHfkd2DiaTLag95EHto20PyOqAAn8g4NILZRINDOiK3V+84+EC6Cp2JcA4jGp2bT/pVLlxKDCFdX5W5VkMAoCcvr1SNTzYSUIbdoeffsWCayQ+F9lQgVQIwC9AflW9qtIYEOop/jPvufD5lrne+HzibZnhacxxvgAt0nK9rrztWveruFKbmG4GJjohDZ8hZW3/A0bdMvarXEnDGfk2Ck/PShj/uBbbYRBxWHFFgoQ4tquQNWkQh2llrZSzO0NxZqqciqwtobHy34QJ4kTJvCmS0CvQtTYDHtx7HI3DxTB6Vxq83sC9BiWR9HjiC+FTrc3Ny6vY93RPpDjJTnXIR6UReyHJO1CimyBNTaSAdJtQogrpHfL6/Vjryok2KWQEY11Zz+AUl7tvC7k2MKaSAe7f6eN8eFKXGnpL5oxhmGLU0jR+0TbYzHzUG/w0gEE4w2c+IU4hwuiXfBByuQ+OZHNvyL+o6bOfBS7Yp5tV5PvzQClTlhGWv2b+1DTx8=
  template:
    metadata:
      creationTimestamp: null
      name: server-passwords
      namespace: udl
    type: Opaque
