apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: db
spec:
  clusterIP: 10.43.100.10
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP
