---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: citadel
spec:
  encryptedData:
    .dockerconfigjson: AgAJZ7D+MWfEG60JVG7R4CwVobAJjlzvGhPJuJc1UBXgbrs7LWxhLsLfGIM+p/b0y0U+lLd3AsnzuneF1s5O+5N4oYbIX0BOvm9KUd/VdKTtsJm6RVXYNyFg3bnG2qoTmHsw9/Pybzaz/II4E+RSoq6u6I84FLb+pjLujfymRD9AgSKnF600JIuYA+rcw4DKtkTrW95Ofo4gw3j9Qm+cTIey7mECpCIZIqqYDrOEDojipkcz82Ee56STpfGO1DoNGzRw9ibjHbLyEDXHpPqyZIU1Iy3ebu7JaFaoj7QYHzKxNGf+hI2V/+FEzLi3I5On5MsvfJPCfvE5mlhVBaYRyc0XQbTah8dxc12H+dPv/Pf36TA7Kq+9GfStzBJvsujKSMVWEHTaiqbovJPrY33q7ussiJPdMHxgQzZ9FVNPPqcyznweY5+n7kFtR4n1JRBqYOTpPJyTlbm/UdT7JypUesOtisORTVrybOYOtqyLLZJ5dBRDJCGwCWeNTJNr9St/fDog6iI0mtE5oIG+c9Gn5jdLNB5vU6kF48eJj3yW2tuUgHYjdGhkE0I6uUtKbtvJrw8hBc7FAl/RH6LgKGm0y57g6Y8ciTdv9k75ZeiT9EO9BXI3vQNe1w9PEXHkCIXwW4AmIBw0npRIP7+0jNBX+hLGMg+nUPo+O1Vd27rc+R5rlSR+TGWznAoD6ILmJIpIte8zCkIRUCZ8DR+lmtqxI/41J2qujxVLO3viC2Jq1IN55xNElyr5sleTPdnwWD49MJ+TMI7uahkXvbQhrr3sZOK2piiOHVRawvTHdAp2ESbq5PSSRz9wDv4Ta6bWnvp5bmHZSRWwwHCzvseyoPUo8e+4e4XVomM5sE+vyePQlnF2l7asW3eKYhNU+LKupmu/ZpCVoLapGvh1BOogsujzpf+FN2MoKsI9FfkCD405HaEheD+sfMcyrbtU/MuMpBWU8uvGrqAEgLkjhKwkpEoSPg==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: citadel
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgC5NTzF92nTfhzIF78B5kON9QnnUe+0+yxZwV+dUELjtk6MfBRMuCG89VUUvm7kFdBfv/kkPRnnTRbQLEwGbAJXpyh+UeOm0gl+vsXTo2Y7BTIG2LFmlqAYbiGXvfzGGC5gm8OuBPe9P2GmRXszisd3lVroRAbqWaj0X88JijgPf6q4f4MCLxTRmVRl17OPnOsRQHxQs11YnpgRUwHgLZAWa1WKRmvmkMPQ+QgpFKF6oNQmLpYiB61aZiodvjw0bDlmgd0u6ib0RLNpqjM3MMZr3mV9UqQ2NgpqeX2IkoxQ2DRiXqFLqBeCPHey7V1iM5iS2jO9itJNt8iSq+fJmciKSt9Hnn+qLpMpebFPDaA6Hr+yGGOfNGWcbr6zpt98dxpDXIEreM9c4n6TstYHR0Sl4TIFUvjr2hnOmFc4RDT3MxOHmHFbkmmDew1os9i2H+Cl84j7yPdD9n+pJzAavvxQii5DnWe/uxiWD7l3xyVB2v64/L2YmKHVqCrqwJKi8vyvzE2YDDHqgCq2DDZ6Zw+tJrGk49641Kj6WHhNOQRcBZOnLWgHqu5OYU/CWCWV0NJ/M5YetRZOgWJSp8R2kJD5DdBQ+KOqwqPvoBMVPdXOMxRT8vsQ4Ve9XoawcbLntwfFW96WK9GTisT/sHozH0eH6NTrfDcuFSKXiUKdovyWIn2+s3jzO9HG9AljgxPkLAPiTVA+BG0e364h4gPwlrKWdafFV0BHc+r+gPNKAzz+Vvha0Q4SfAAVbf8xp3bv4+EPTthC3VRfV3sqOJ8f9Z5fnWeZQC+vCBw0ffqO2VIK3ZlSGdXVG1fw6iPspn77reyuIu6iJgZxCRK4ebJsK08779RC5IxBbiHowg8nZ3iez83ewAbRM8EvzLCeMplvJvDtiLM6VP0Bmov9Tf+zjPHWmR7AFnBm691sOe29JTHIePHF9mifRQ63c4ws3d2GK+AE71o+aJwVRPVAKOrb7Q==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
