---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: citadel
spec:
  encryptedData:
    .dockerconfigjson: AgBKQpUI3GbKBPOunAFLFicsVOBgbtfW//y+flweZ3dVyrUA28u6/eHQR0bxPO4a70mHRrWyo83r+t6fI15D4kOkYUXm5R6kV/9uZ8iqqnxWmfRROtjbQJfVSlzI9MazqAUCmWFl5+QHJIIDHRfPbZBzeEShWRMD2GscGG1L9JjoIPfNd5nfH/TkMMvqBpwWBDcJJrp+9YP+g8zv+p78CZRHhcLapF0WJ4nBrFpci4CKkpn3YJjbCTSSnza9CDDmpV61HYtvEabrfQnf+7KowQQ9GVf6NOeEiySaKvfi/pqOlp2bNCz2Wd1RVRey62wAF5mKskV/ClOBAi/ukeEa0HoyNB2yau57PNaQ+qL/ThXJDS3K6QlcigTRgBJHFBmh5HIzwOK6M3yNbLKo3/qKhlHPU622QNSlod+RBT5WT9pJdUKBZYNejI8ltM8WRvXecRc2AvaweX87kLY9IXV05mlNciWU+YHQiu0BxD8VPTKDHgWmB4cvc973KpglcQRDespTtCnUcQM6adglG6sp7jdYjEJiBH2McWOLkjXtmaCqPQnvRjzCIMniczrRQuLbayC0WfzOoIB8ICEAtdUjQlzmzkA++RwWql1Na+KHoB6KuIK42aJNl4EtRt7YSDNkdP3ALK1JAsyZMwBGABRoKGZZmTIBObJ9DurRsr6sfqxxHWD5UgIiRKNnPb/Gf3Mja50as+QTwnVfmNLWo3J3SRwrTk/pb0VyUB/2yBbg10CQwHFL8lVZwZLiOLrPi093kOxx+nWY6CmaZ6zra+m18+kXG8TN6UMp5E7QzSbFs7Xxpk1XMit2i/vbQFEkBliTf/wVh+VzfinQM0KjPqocJ0uLx87jRRWyQmSRlRbnCi6cRMGy1JuGaKeLJ6Ii6BpUkR2UuDKoDcKFdEoUg4dZ/E4e9lzsXWi/Cd7uuUYQsuljPHbCJdCLmbnj6IaK+8lNsIZUNKgV2lufwRC0AzO8hQ==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: citadel
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAaKMF4yFkWIdlEP+MjCl6oI9sNrGASJNFn/XposXXjWn7Vvt7/toXCN7XzgyWoheTlEKawhCsiPqy4Ihbu0KqSRYpD1eiiHneT4AlYI1MFFNhbm7L+utr9MhqeZR1dTJEG2oIUxatENTPnuomo5s9QbOaMZuzk+0VzDgcG1x6jYDTszarFDjaHr6DyLIOU+k6yXFpQRlj2sLTwvhz4n7rTjbaR6u8J4g/epaMXIxxGEJsg+8ykx5V3hcPwr+BwyiT9DEh4g6vUkFTgHvvp5KTSJtal2bYtDfMswZHlDIBnDXTAIx0yVR2qz+ZEuCVLb23XdhWQaGfQALbv0MA9O92T+X3x2acwUlcaqq7l6nJYS2u0oq1rJZx1P0iji6SvQYlwahrhtbYt6CXXkeomf7+kikZ63LZKbNG2fsCoNRadpUS8xUdT7FK+vkEnSlCOPcbMSRj8tQLAOfnItB7Oufa/DUqLvMmxNKIcAlNO77SsTS1e4+JBsxfJpiLgjqf9QPHefYCcrYrvdL4xeYtY/ij5H1btuVLqH4zRWZ/Ry9KxhJ/OiOUmsI8aSLijg6JvwazTHk4aoOkK/kMEQi6T06Eq6zVWGPmm8HcE4oAmgJvzgVHsZpo2KE/DC9y5aaVH2++DLVTgK+/B6S9624qg+tmT9o5M1kkq9HjrNhsLeiu5K9Kt04gKX9b0uGrLPSQA9by9MuwPuFYGabouvGlvRPdOa/fGezX8LDVPfftJL4YdS6jE3vLsgp/4oc6AWfAalK/ASA+AVHrBNPuWKQLj62JI0SG6j8jsYqDU5UXiuYRB0nyIwQJhonwmQ2aXtFeeWn0WnTmzLzs5/tXRg2T/m4MsR5WqKnF/OhxIPiL4MXIQJavLZcXiZqL2Jpz92cct+Q5uQ6sfhn5ebS+dx55fgIDsDmBHlRwkjRHJzVrmtSDhth1s3T+yOhrTNxEvGzA9AlL//g7c9EmvzzCCtljx0g==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
