---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: citadel
spec:
  encryptedData:
    .dockerconfigjson: AgB4pxFJHwO2Oqs1Zd1cqlkUYoDQPCGNad0kzhEjbjXLpORnpxNF/2OoM6pdseJ2zQjJcjbyi/8y64gT+CQHE3tMDulZsFuf9o0rwdAiHGQn+/w5gru2ZFGCns3UAxJwLWAXjmL8d0TzTdxHJuk7S3WphT1ajvHmfir9hXkoAlVQuYYd7ImxSjwDYDK4cCVE6TjK89uWE2EA547dexcpxN6EpTASetBL9S1ZgLaK9zyRjxH+C/tieiOuRnm3UgnbFqMTT48N8wHnU1nlchzs+noIladr/qd+vnzfaeWfiiZqF7huxVEtHEx3oEftI268DWJKFZX4/JVMoXDghJiHISNc3RbeZzZB40rWELdJkfLXTGSJXbHA+iO6clfoeEcILMQYKR8H3Q/klr3QJTNkFR68uplActzYdzqrEpkOoruW7A5HVHWJNK0gzNkaRJDm8kCXjiJ0RoXcMOeBhEE2dbdz2WaPEi/n90IM+nDhuBm5Fl5mV4GmG/gTJvDSIIkHNo1jVBC8/xX9bX9GSMgtQEHfiqaCZ6s4ZVTAvv/A6NDK4nG776UmOu2hXOhI+xq8pTRLjTGsHq3HHzfI8/IU/hX1OuWCQ2yk4MDdr1mBbIQP6YhXMx+xjlJ7wC8GYduXCVedcHXMB9qbO7Gxf3w5gW8P4+mjQBa0WaXSdmHzVygttB74bwrlbtruKoShXD8fYW5jd4Y3hLaZBrznyNXhx5p5V1v0KHtSEBLwdpzXrq7eEZqAaudMXv82Vu7bfR5Ulk6tvSM1LiXWbwf/8b43X8xd8eRcGqXiif+MEQ9pnR5XWFOoMTy6CIAOCUiVarAZb7S+yOUYKh1Zl3FXOvTLux2qtPYi0Ed2tGuH8xfaCjRZzNuQUBQak25lHiW5MkSmggqXdvor9AY9WahGVe1M+0hSaj5MmA4F+QIYTdOXYNgjjAwknBvRkfWWGhfe3EOE3Mmp2Q+nDIoOQ+wwExETJA==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: citadel
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBCAvZ8fypBZRKZA02kxVSy2gDJUd4qWJVne0Ms/upp6aCTSWXqN8f7CfUwA45RwP5mS5pvjY2TsX6MsGYMQev8EE9TsWdEBT/Z5FXJEBqsev7pPMXl47AO+uoo/Snq0+Wgbpqu3bZ0ClQd9AGss3LLdJpGPgTp2IIgxwakyCXGcGQ1ZZBs2VUj76aDqfrFZyoxirBJSLMRBu5DTyFfegf7gmUTVmVayY+EDRroTcV+PbIIHWXzCuvSIizEnprYGD87Nr7HW0uW2hclyzHVfT7NcefR8HYx525jG3MPN3fI1sNvnz2kot9D2ly43Jnh2Nyo/WGxPOHEa7uaRpoVzk/uQ8vF+ZC1xjv6gLwzIi/08gIEOmv/sAQUqftNqSCvh1kl3rnprXa69NiKQ41vvky576wLs1sOI+Tv4SRFQeBa9c6wpHnUOKb5uWmHSllw1A1ATX+IiqPstJvI3QGNZqemrPreDP9y2EUnzngKq+ZoQlbIad8FAzcYoNNZSLA73uAFkxsWOaoY4Xgz4uaRbOaV5n/NfEEEpRN0vn1v4X2rHyJUJoN/Po9nB6Opdfw9xV0+yvEQBh5o2BcHvbEnYU5/dNGIrsaR6Z+lVbxjh8VYjrwo/ibIfkyI4OGXZAqVaNmzZiQmlJRJhI4nUDFeTrLFlnabzMNeDaUs5KnMrnvRyJ2PYcWNOrXqzU425VkaUU2Y73nSJoREkwuQpS5upXEZEcyHW8CBwSlxflJp7KLEiAvr/5r5VAngVLO6cvOxWgHqeIafUmRQh3UNVRL5XSCNHf28m+E2a5az73VPsympwe0TImCQBbzjauqL6+QoCM4DTU+PGDmNUvz6dQD8iP/bkINvEq+yhHnBOLKWPlmBLr7QYEDWzltMpLdu76jxIiHQnuPQNwr8ICnMbrUHHRj3MOx/ntn1NddkUJPqEUBT/6VXAvV2bWeCtd/KBvW+TGA2cASO0nF7jhLKT5wxYw==
  template:
    metadata:
      annotations:
        description: GitHub Container Registry login secret for private images
        sealedsecrets.bitnami.com/controller-name: sealed-secrets-controller
        sealedsecrets.bitnami.com/controller-namespace: kube-system
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
