---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-restarter
  namespace: udl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restarter
  namespace: udl
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restarter
  namespace: udl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restarter
subjects:
  - kind: ServiceAccount
    name: deployment-restarter
    namespace: udl
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-git-sync-serverfiles
  namespace: udl
spec:
  schedule: "0 */3 * * *"  # Every 3 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-restarter
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - kubectl rollout restart deployment/git-sync-serverfiles -n udl
