apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: ">=1.14.0"
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 10m
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    installCRDs: true
    replicaCount: 1
    global:
      leaderElection:
        namespace: cert-manager
